name: Docker Image CI

on:
  push:
    branches:
      - main  # or any other branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/ravikantchauhan/phpmyadmin-docker/phpmyadmin-docker:latest .
          docker push ghcr.io/ravikantchauhan/phpmyadmin-docker/phpmyadmin-docker:latest

      - name: Log out from Docker Hub
        run: docker logout ghcr.io
